[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".zsh/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".zsh/plugins/zsh-z"]
    type = "archive"
    url = "https://github.com/agkozak/zsh-z/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".gitignore"]
    type = "file"
    url = "https://www.toptal.com/developers/gitignore/api/linux,macos,vim,python"
