[hostname]
ssh_symbol = ""

[character]
error_symbol = "[✖](bold red)"

[directory]
truncate_to_repo = false
truncation_length = 2

[python]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true
